ignore:
  - "**/swingGUI.scala"
  - "**/fxGUI.scala"
  - "**/TileLabel.scala"
  - "**/fenDemo.worksheet.sc"
  - "**/model.worksheet.sc"
  - "**/TileLabel.scala"
  - "**/Chess.scala"
  - "**/resources/"
  - "**/fileIOComponent/**"

coverage:
  status:
    patch:
      default:
        target: 85%
